### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by ArjixWasTaken** [AkaraChen/user-scripts#1]
Consider naming ur userscripts using the `xxx.user.js` name format, it is kinda the standard.

Also, when adding keyboard shortcuts to sites, you should prefer to use the `keyup` event, as it is only fired once.
The `keydown` event is fired repeatedly until the user stops pressing that key.

In your telegram script it may not matter, since you only call `.focus()` and are not doing anything intensive.
(You could have a boolean to make it so you only `.focus()` on the first `keydown` event and not the subsequent ones)

PS: Feel free to ~~steal~~ borrow code from [my userscripts](https://github.com/ArjixWasTaken/my-userscripts)!

My utils:
- [`waitForElem`](https://github.com/ArjixWasTaken/my-userscripts/blob/main/vuemastery-lesson-copier.user.js#L44-L53) (interval implementation)
- [`waitForElem`](https://github.com/ArjixWasTaken/my-userscripts/blob/main/MyFreeMp3JuicesYTintegration.user.js#L65-L91) (observer implementation)
- [`onLinkChange`](https://github.com/ArjixWasTaken/my-userscripts/blob/main/vuemastery-lesson-copier.user.js#L17-L33) (for PWAs)
- [`createElement`](https://github.com/ArjixWasTaken/my-userscripts/blob/main/youtube-music-enhancer.user.js#L85-L97)
- - Usage: `createElement("div", { children: [ createElement("p", { innerText: "Hi there!" }) ] })`

Third party utils:
- [`fetch`](https://github.com/Vendicated/Vencord/blob/main/browser/GMPolyfill.js) (polyfill for tampermonkey)

**Comment by ArjixWasTaken** [comment]
Also, most userscript distribution sites support automatic updates from GitHub using webhooks.
If you consider uploading to greasyfork or openuserjs that is the best way to do it.

**Comment by AkaraChen** [comment]
Thank you very much for your help☺️.

it's very helpful for people like me who are new to user script.

Will modify my script later this week.
